name: Deploy Infrastructure and Configure Servers
run-name: Deploy by 🚀 ${{ github.actor }} 🤖
on:
  push:
    branches:
      - main
    tags:
      - deploy
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  TF-Build-and-Test:
    uses: karimkarimson/actions-ansible/.github/workflows/tfbuildtest.yml
    with:
      secrets: inherit

  TF-Deploy-and-Upload:
    runs-on: ubuntu-latest
    needs: TF-Build-and-Test
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - run: terraform -chdir=./terraform init
      - run: terraform -chdir=./terraform apply --auto-approve

      - name: Upload Infrastructure Files for Ansible Hosts 
        uses: actions/upload-artifact@v3
        with: 
          name: datapass
          path: |
            ./terraform/datapass

  Ansible-Node-BuildandTest:
    uses: karimkarimson/actions-ansible/.github/workflows/ansiblebuildtest.yml
    with:
      secrets: inherit

  Deploy-and-Upload:
    runs-on: ubuntu-latest
    needs:
      - Ansible-Node-BuildandTest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        name: datapass
        with:
          path: ~/

      - name: Use Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./ansible/playbooks/playbook.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory ./ansible/hosts.ini