name: Terraform BuildTest
run-name: by 🚀 ${{ github.actor }} 🤖
on: 
  workflow_call:
   secrets:
    AWS_SESSION_TOKEN:
      required: true
    AWS_ACCESS_KEY:
      required: true
    AWS_SECRET_KEY:
      required: true

env:
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  TF-Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
      - run: terraform version
      - run: terraform -chdir=./terraform init
      - run: terraform -chdir=./terraform validate
      - run: terraform -chdir=./terraform plan